networks:
  exporter-net:
    name: exporter-net
  monitor-net:
    name: monitor-net

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/certs:/etc/nginx/certs
    networks:
      - exporter-net
      - monitor-net
